name: proxyapp

services:
  proxy:
    image: nginx:1.26.1-alpine3.19
    ports:
      - 3000:80
    networks:
      - proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  frontend:
    image: node:20.15.1-alpine3.20
    container_name: frontend
    command: npx serve -p 3000 /app
    expose:
      - 3000
    networks:
      - proxy
    volumes:
      - ./frontend:/app:rw
  backend:
    image: node:20.15.1-alpine3.20
    container_name: backend
    command: node /app/index.js
    expose:
      - 4000
    networks:
      - proxy
    volumes:
      - ./backend:/app:rw

networks:
  proxy:
